Start of development
wirenboard/wb-mge pull request #1
Opened 2024-09-02 16:31 UTC by AlexeyStrizhnev

В main для примера реализованы колбек-функции, которые принимают данные из одного интерфейса и отправляют в другой. Если нет ячейки с именем хоста, то считаем, что флешка чистая и устанавливаем (сохраняем во флеш) дефолтные значения. Serial настраивается из хранилища. Остальные настройки пока просто прописаны руками. Все возможные настройки устройства прописываются руками в массив `setting_item_t setting_items[]` в конце файла `setting_items.c` (на данный момент прописаны далеко не все). Для юнит-тестов `setting_items_test.c` реализовано простое хранилище в оперативной памяти `ram_storage.c`, которое имеет функции, аналогичные `nv_storage.c`. В `http_server.c` реализованы основные обработчики запросов файлов index.html, favicon.ico и обработчики на чтение/запись настроек `settings_get_handler` и `settings_post_handler`, а также обработчик запроса дескриптора SSDP.

2024-09-16 10:33 UTC, ad7718 requested changes

2024-09-16 10:33 UTC, ad7718 commented on main/http_server.c
> +            // Serious Error: Abort OTA
Тут уехало немного

2024-09-16 10:33 UTC, ad7718 commented on main/ethernet.c
> +#define ETH_PHY_LAN87XX 1
Здесь надо значения выровнять табами, по нашему кодстилю

2024-09-16 10:33 UTC, ad7718 commented on main/http_server.c
> +    if (esp_ota_end(ota_handle) != ESP_OK || esp_ota_set_boot_partition(ota_partition) != ESP_OK) {
Тут по нашему код стилю нужно расставить скобки

2024-09-16 10:33 UTC, ad7718 commented on main/main.c
> +            ESP_LOGI(TAG, "Ethernet HW Addr %02x:%02x:%02x:%02x:%02x:%02x",  //
О чем говорит комментарий в этой строке?

2024-09-16 10:33 UTC, ad7718 commented on main/main.c
> +    snprintf(default_hostname, SETTING_ITEM_MAX_STR_LEN, "%s-%02X%02X%02X", BASE_HOSTNAME, mac[3], mac[4], mac[5]);
может немного поменьше уникальности? у роутеров tp-link например в названии точки доступа 2 байта мака

2024-09-16 10:33 UTC, ad7718 commented on main/nv_storage.c
> +    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
здесь нужно скобки расставить по нашему кодстилю

2024-09-16 10:33 UTC, ad7718 commented on main/serial.h
> +typedef struct {
у нас по кодстилю нужно "struct serial_config" и там где используется писать "struct serial_config..."

2024-09-16 10:33 UTC, ad7718 commented on main/serial.c
> +#define SERIAL_PORT_NUM 2
здесь нужно расставить табы

2024-09-16 10:33 UTC, ad7718 commented on main/serial.c
> +#elif CONFIG_IDF_TARGET_ESP32S3
после elif нужны отступы

2024-09-16 10:33 UTC, ad7718 commented on main/serial.c
> +#define SERIAL_BUF_SIZE (1000)
табы. Почему 1000? Этого точно хватит?

2024-09-16 10:33 UTC, ad7718 commented on main/serial.c
> +serial_receive_handler_t receive_handler = NULL;
static

2024-09-16 10:33 UTC, ad7718 commented on main/serial.c
> +static const char *TAG = "serial";
это после дефайнов должно лежать по нашему кодстилю

2024-09-16 10:33 UTC, ad7718 commented on main/serial.c
> +esp_err_t serial_send(uint8_t *data, uint8_t len) { return uart_write_bytes(SERIAL_PORT_NUM, (const char *)data, len); }
здесь нужно нормально функцию отформатировать, по нашему кодстилю

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.h
> +#define SETTING_ITEM_NUM_MAX 50
табы

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.h
> +typedef enum {
"enum setting_item_type" нужно писать по нашему кодстилю

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.h
> +int setting_items_set_defaults();
по нашему кодстилю нужно обязательно указывать тип передавамого значения

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +#define UART_BAUD_RATE_MIN 300
табы

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +setting_item_iface_t iface;
static

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +char default_hostname[SETTING_ITEM_MAX_STR_LEN] = {0};
в этой группе все должны быть static

Переменная называется default_hostname и по логике имени должна быть const, но в неё потом что-то копируется

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +    if (strcmp(str, "1-bit") == 0) {
эту и подобные строки нужно как миниму задефайнить, а лучше положить в static const массив, чтобы не дублировать их во флэш

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +            strcpy(str, "1-bit");
предлагаю везде испольовать безопасные функции strncmp, strncpy, ...

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +            if (ip_arr[i] < 0 || ip_arr[i] > 255) {
нужно добавить скобки по нашему кодстилю

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +            *ip = ((uint32_t)((ip_arr[0]) & 0xff) << 24) | ((uint32_t)((ip_arr[1]) & 0xff) << 16) | ((uint32_t)((ip_arr[2]) & 0xff) << 8) |
я бы сделал 2 условия на одной и два на другой строке, так строчка короче будет

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +    if (setting_item_iface->save_bool == NULL || setting_item_iface->save_num == NULL || setting_item_iface->save_str == NULL ||
здесь нужно собки расставить по кодстилю

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +    for (int i = 0; i < sizeof(setting_items) / sizeof(setting_items[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +    for (int i = 0; i < sizeof(setting_items) / sizeof(setting_items[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +    for (int i = 0; i < sizeof(setting_items) / sizeof(setting_items[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +        .default_value = "1-bit",
опять же, здесь то же самое значение, я бы брал из const массива

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +        .default_value = "192.168.5.1",
почему 5.1?

2024-09-16 10:33 UTC, ad7718 commented on main/ssdp.h
> +#pragma once
Этот модуль нужно заменить на другой из-за лицензии GPL

2024-09-16 10:33 UTC, ad7718 commented on main/tcp_client.c
> +// #include "sdkconfig.h"
это удали, если не нужно

2024-09-16 10:33 UTC, ad7718 commented on main/tcp_client.c
> +#define RX_BUFFER_SIZE 1024
табы

2024-09-16 10:33 UTC, ad7718 commented on main/tcp_client.c
> +tcpc_receive_handler_t tcp_client_receive_handler = NULL;
static

2024-09-16 10:33 UTC, ad7718 commented on main/tcp_client.c
> +        while (1) {
здесь с вайлами не перебор? не получится как-то по-другому?

2024-09-16 10:33 UTC, ad7718 commented on main/tcp_client.c
> +    strcpy(ip, host_ip);
strncpy

2024-09-16 10:33 UTC, ad7718 commented on main/tcp_server.c
> +#define KEEPALIVE_IDLE 5
табы

2024-09-16 10:33 UTC, ad7718 commented on main/tcp_server.c
> +tcps_receive_handler_t tcp_server_receive_handler = NULL;
static

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.h
> +#pragma once
есть ощущение что можно сделать этот модуль компактнее, позже еще посмотрю

2024-09-16 10:33 UTC, ad7718 commented on main/tcp_server.c
> +        struct sockaddr_storage source_addr;  // Large enough for both IPv4 or IPv6
у нас ipv6 вообще есть? по-моему не нужен

2024-09-16 10:33 UTC, ad7718 commented on main/wifi_apsta.h
> +typedef struct {
struct wifi_apsta_config

2024-09-16 10:33 UTC, ad7718 commented on main/wifi_apsta.c
> +#define WIFI_CHAN_AP 1
табы

2024-09-16 10:33 UTC, ad7718 commented on main/wifi_apsta.c
> +    } else if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on main/wifi_apsta.c
> +    } else if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on main/wifi_apsta.c
> +        // ESP_LOGI(TAG, "connected to ap SSID:%s password:%s", wifi_config_sta.sta.ssid, wifi_config_sta.sta.password);
это наверно можно раскомментить, просто пароль не печатать

2024-09-16 10:33 UTC, ad7718 commented on main/wifi_apsta.c
> +        if (strlen(apsta_cfg->ap_pass) == 0) {
strnlen

2024-09-16 10:33 UTC, ad7718 commented on main/wifi_apsta.c
> +        memcpy(&wifi_config_ap.ap.ssid, apsta_cfg->ap_ssid, strlen(apsta_cfg->ap_ssid));
strnlen

2024-09-16 10:33 UTC, ad7718 commented on main/wifi_apsta.c
> +        memcpy(&wifi_config_ap.ap.password, apsta_cfg->ap_pass, strlen(apsta_cfg->ap_pass));
strnlen

2024-09-16 10:33 UTC, ad7718 commented on main/wifi_apsta.c
> +        memcpy(&wifi_config_sta.sta.ssid, apsta_cfg->sta_ssid, strlen(apsta_cfg->sta_ssid));
strnlen

2024-09-16 10:33 UTC, ad7718 commented on main/wifi_apsta.c
> +        memcpy(&wifi_config_sta.sta.password, apsta_cfg->sta_pass, strlen(apsta_cfg->sta_pass));
strnlen

2024-09-16 10:33 UTC, ad7718 commented on unittests/common.h
> +#define COLOR_RED "\033[0;31m"
табы

2024-09-16 10:33 UTC, ad7718 commented on unittests/common.h
> +#define PRINT_E(TEXT) COLOR_RED TEXT COLOR_RESET
табы

2024-09-16 10:33 UTC, ad7718 commented on unittests/common.h
> +#define TEST_OK 0
табы

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.h
> +esp_err_t rams_write_u8(const char* key, uint8_t value);
include stdint

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +#define SETTING_ITEM_NUM_MAX 100
табы

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +typedef enum {
enum value_type

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +typedef struct {
struct storage_item

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +storage_item_t storage[SETTING_ITEM_NUM_MAX];
static

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +        if (storage[i].key[0] == '\0' || strcmp(storage[i].key, key) == 0) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +        if (strcmp(storage[i].key, key) == 0 && storage[i].type == TYPE_STR) {
strncmp и скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +        if (storage[i].key[0] == '\0' || strcmp(storage[i].key, key) == 0) {
strncmp и скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +        if (strcmp(storage[i].key, key) == 0 && storage[i].type == TYPE_U8) {
strncmp и скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +        if (storage[i].key[0] == '\0' || strcmp(storage[i].key, key) == 0) {
strncmp и скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +        if (strcmp(storage[i].key, key) == 0 && storage[i].type == TYPE_U16) {
strncmp и скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +        if (storage[i].key[0] == '\0' || strcmp(storage[i].key, key) == 0) {
strncmp и скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +        if (strcmp(storage[i].key, key) == 0 && storage[i].type == TYPE_U32) {
strncmp и скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/mocks/driver/uart.h
> +typedef enum {
enum uart_stop_bits, остальные тоже

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    for (int i = 0; i < sizeof(valid_test_baudrate) / sizeof(valid_test_baudrate[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    for (int i = 0; i < sizeof(invalid_test_baudrate) / sizeof(invalid_test_baudrate[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    for (int i = 0; i < sizeof(valid_test_parity) / sizeof(valid_test_parity[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    for (int i = 0; i < sizeof(invalid_test_parity) / sizeof(invalid_test_parity[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    const char* valid_test_databits[] = {"5-bit", "6-bit", "7-bit", "8-bit"};
эти значения наверно можно прямо из const массива тестируемого модуля взять чтобы не ошибиться

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    for (int i = 0; i < sizeof(valid_test_databits) / sizeof(valid_test_databits[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    for (int i = 0; i < sizeof(invalid_test_databits) / sizeof(invalid_test_databits[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    for (int i = 0; i < sizeof(valid_test_stopbits) / sizeof(valid_test_stopbits[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    for (int i = 0; i < sizeof(invalid_test_stopbits) / sizeof(invalid_test_stopbits[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    for (int i = 0; i < sizeof(valid_test_ip) / sizeof(valid_test_ip[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    for (int i = 0; i < sizeof(invalid_test_ip) / sizeof(invalid_test_ip[0]); i++) {
скобки

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    if (setting_items_init(&setting_item_iface) != 0) {
тут функция ожидает второй параметр, похоже тест неактуальный, нужно поправить

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +    // for (int i = 0; i < num_keys; i++) {
это удали, если не нужно

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +}
новая строка вконце

2024-09-16 10:33 UTC, ad7718 commented on main/setting_items.c
> +    int ret = snprintf(str, IP_ADDR_STR_LEN, "%lu.%lu.%lu.%lu", ip & 0xFF, (ip >> 8) & 0xFF, (ip >> 16) & 0xFF, (ip >> 24) & 0xFF);
%lu in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +            TEST_FAILED("Failed to save baudrate %d", expected_baudrate);
%lu in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +            TEST_FAILED("Expected %d, got %d", expected_baudrate, got_baudrate);
%d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.

2024-09-16 10:33 UTC, ad7718 commented on unittests/setting_items_test.c
> +            TEST_FAILED("Saved invalid baudrate %d", invalid_baudrate);
%d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.

2024-09-16 10:44 UTC, ad7718 commented on main/setting_items.c
> +    int ip_arr[IP_ADDR_NUM + 1] = {0};
почему +1?

2024-09-16 12:05 UTC, ad7718 commented
Нужна задача watchdog_task

2024-09-16 12:09 UTC, ad7718 commented on main/serial.h
> +esp_err_t serial_init(serial_config_t *serial_config, serial_receive_handler_t serial_receive_handler);
это почему-то совсем не используется. у тебя были зачатки мостовой части, ты её совсем убрал?

2024-09-16 12:18 UTC, ad7718 commented
Сейчас прошивка собирается с -Og, нужно сделать чтобы в продакшне собиралось с -Os, также нужно сделать чтобы её нельзя было считать

2024-09-16 12:45 UTC, ad7718 commented on .gitignore
> +sdkconfig**
Сейчас используется дефодтный sdkconfig, как я пноял, нужно добавить его в репозиторий и настролит как написано тут https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/kconfig.html

В файле предлагаю настроить: тактовую частоту, уровень оптимизации, защиту от чтения прошивки, fatfs выключить и использовать spiffs (у spiffs встроенный wear leveling, для fafts там сверху что-то дописали скорее всего), выключить mqtt, выключить поддержку float в unity, отключить поддержку директорий в ФС, возможно что-то еще, нужно повнимательнее посмотреть что предлагает "idf.py menuconfig"

2024-09-17 10:39 UTC, AlexeyStrizhnev commented on main/http_server.c
> +            // Serious Error: Abort OTA
Сделано

2024-09-17 10:40 UTC, AlexeyStrizhnev commented on main/ethernet.c
> +#define ETH_PHY_LAN87XX 1
Сделано

2024-09-17 10:40 UTC, AlexeyStrizhnev commented on main/http_server.c
> +    if (esp_ota_end(ota_handle) != ESP_OK || esp_ota_set_boot_partition(ota_partition) != ESP_OK) {
Сделано

2024-09-17 10:40 UTC, AlexeyStrizhnev commented on main/main.c
> +            ESP_LOGI(TAG, "Ethernet HW Addr %02x:%02x:%02x:%02x:%02x:%02x",  //
Убрал комментарий

2024-09-17 10:41 UTC, AlexeyStrizhnev commented on main/main.c
> +    snprintf(default_hostname, SETTING_ITEM_MAX_STR_LEN, "%s-%02X%02X%02X", BASE_HOSTNAME, mac[3], mac[4], mac[5]);
Женя против

2024-09-17 10:41 UTC, AlexeyStrizhnev commented on unittests/setting_items_test.c
> +}
Сделано

2024-09-17 10:41 UTC, AlexeyStrizhnev commented on main/setting_items.c
> +    int ret = snprintf(str, IP_ADDR_STR_LEN, "%lu.%lu.%lu.%lu", ip & 0xFF, (ip >> 8) & 0xFF, (ip >> 16) & 0xFF, (ip >> 24) & 0xFF);
С тобой обсудили. Оставляем.

2024-09-17 10:50 UTC, AlexeyStrizhnev commented on unittests/setting_items_test.c
> +            TEST_FAILED("Failed to save baudrate %d", expected_baudrate);
Тут наверно про %d. Сделано.

2024-09-17 10:50 UTC, AlexeyStrizhnev commented on unittests/setting_items_test.c
> +            TEST_FAILED("Expected %d, got %d", expected_baudrate, got_baudrate);
Сделано.

2024-09-17 10:50 UTC, AlexeyStrizhnev commented on unittests/setting_items_test.c
> +            TEST_FAILED("Saved invalid baudrate %d", invalid_baudrate);
Сделано.

2024-09-17 10:50 UTC, AlexeyStrizhnev commented on main/setting_items.c
> +    int ip_arr[IP_ADDR_NUM + 1] = {0};
Добавил комментарий.

2024-09-17 10:51 UTC, AlexeyStrizhnev commented on main/serial.h
> +esp_err_t serial_init(serial_config_t *serial_config, serial_receive_handler_t serial_receive_handler);
Да, будет использоваться позже.

2024-09-17 10:53 UTC, AlexeyStrizhnev commented on .gitignore
> +sdkconfig**
Частично решено. Добавил sdkconfig.defaults с необходимыми СЕЙЧАС настройками. Создал задачу в ютрак.

2024-09-19 10:36 UTC, ad7718 requested changes
Много незакрытых замечаний, почитай внимательно наш кодовый стиль

2024-09-19 10:36 UTC, ad7718 commented on main/serial.h
> +esp_err_t serial_init(serial_config_t *serial_config, serial_receive_handler_t serial_receive_handler);
Давай TODO в код

2024-09-19 10:36 UTC, ad7718 commented on main/setting_items.c
> +    int ip_arr[IP_ADDR_NUM + 1] = {0};
Почему массив называется ip_arr? Если это array, то такой постфикс не нужен, если имелось ввиду addr, то нужно исправить

2024-09-19 10:36 UTC, ad7718 commented on main/ethernet.c
> +#define ETH_PHY_LAN87XX  1
У нас табы 4 пробела, нужно везде исправить

2024-09-19 10:36 UTC, ad7718 commented on main/setting_items.c
> +    if (setting_item_iface->save_bool == NULL || setting_item_iface->save_num == NULL || setting_item_iface->save_str == NULL ||
скобок не появилось, посмотри кодстиль

2024-09-19 10:36 UTC, ad7718 commented on unittests/mocks/ram_storage.h
> +esp_err_t rams_write_u8(const char* key, uint8_t value);
инклуда не хватает по прежнему

2024-09-19 10:36 UTC, ad7718 commented on unittests/setting_items_test.c
> +    char* valid_test_databits[] = {"5-bit", "6-bit", "7-bit", "8-bit"};
почему оно перестало быть const? Нельзя все возмодные значения параметров объявить в одном месте и не писать одинаковые строки по разным модулям?

2024-09-19 10:36 UTC, ad7718 commented on main/ethernet.c
> +#define ETH_PHY_LAN87XX 1
надо везде использовать нормальный таб, у нас 4 пробела

2024-09-19 10:36 UTC, ad7718 commented on main/setting_items.c
> +    int ret = snprintf(str, IP_ADDR_STR_LEN, "%lu.%lu.%lu.%lu", ip & 0xFF, (ip >> 8) & 0xFF,
скобки нужны

2024-09-20 07:46 UTC, AlexeyStrizhnev commented on main/setting_items.c
> +    int ret = snprintf(str, IP_ADDR_STR_LEN, "%lu.%lu.%lu.%lu", ip & 0xFF, (ip >> 8) & 0xFF,
Сделано

2024-09-20 07:47 UTC, AlexeyStrizhnev commented on unittests/setting_items_test.c
> +    char* valid_test_databits[] = {"5-bit", "6-bit", "7-bit", "8-bit"};
Const вернул. Добавил файл с константами.

2024-09-23 09:03 UTC, ad7718 requested changes

2024-09-23 09:03 UTC, ad7718 commented on main/setting_items.c
> +            if (octets[i] < 0 || octets[i] > 255) {
скобок не хватает

2024-09-23 09:03 UTC, ad7718 commented on unittests/common.h
> +#define TEST_OK     0
обычно стараемся чтобы все группы дефайнов были одинаково выровнены табами

2024-09-23 09:03 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +        if (strcmp(storage[i].key, key) == 0 && storage[i].type == TYPE_STR) {
strncmp

2024-09-23 09:03 UTC, ad7718 commented on main/serial.c
> +#define SERIAL_BUF_SIZE (1000)
хотелось бы комменты к размерам буферов, почему такие выбраны, здесь и в http

2024-09-23 09:03 UTC, ad7718 commented on main/http_server.c
> +#define REQ_RECV_BUF_SIZE       1024
нужен коммент почему такой буфер, хватит ли его

2024-09-23 09:03 UTC, ad7718 commented on unittests/setting_items_test.c
> +        if (strcmp(expected_str, got_str) != 0) {
давай здесь везде тоже безопасные strncmp/strncpy

2024-09-23 09:03 UTC, ad7718 commented on main/constants.h
> +// Значения по умолчанию
это предлагаю вынести в config.h

2024-09-23 09:03 UTC, ad7718 commented on main/constants.h
> +#define BASE_HOSTNAME               "WB-MGE"
это предлагаю перенести в config.h

2024-09-23 09:03 UTC, ad7718 commented on main/constants.h
> +#pragma once
этот файл предлагаю переименовать в settings_items_const.h

2024-09-23 09:19 UTC, ad7718 commented on main/setting_items.c
> +static bool save_boudrate(const char *key, const void *value)
baudrate

2024-09-23 09:28 UTC, ad7718 commented on main/setting_items.c
> +static bool save_databits(const char *key, const void *value)
сейчас эта функция делеат почти то же, что и save_stopbits, и тут много таких других, нужно убрать копипасту

2024-09-23 09:29 UTC, ad7718 commented on main/setting_items.c
> +    if (bridge_port < 1024) {
нужен дефайн для 1024, непонятно почему 1024

2024-09-23 09:34 UTC, ad7718 commented on main/setting_items.c
> +    for (int i = 0; i < (sizeof(setting_items) / sizeof(setting_items[0])); i++) {
sizeof(setting_items) / sizeof(setting_items[0]) нужно выделить в макрос #define COUNT_OF(x) ...

2024-09-23 09:35 UTC, ad7718 commented on unittests/setting_items_test.c
> +    for (int i = 0; i < (sizeof(valid_test_baudrate) / sizeof(valid_test_baudrate[0])); i++) {
здесь тоже везде нужен макрос #define COUNT_OF(x) ...

2024-09-23 09:39 UTC, ad7718 commented on unittests/mocks/esp_mac.c
> +    {
тут скобка не на своём месте

2024-09-23 09:55 UTC, ad7718 commented on main/main.c
> +    char default_hostname[SETTING_ITEM_MAX_STR_LEN] = {0};
давай назовём unique_hostname или generated_hostname, я долго думал почему оно default и не const, в библиотеке settings_items тоже

2024-09-23 09:56 UTC, ad7718 commented on main/setting_items.c
> +int setting_items_init(char *def_hostname, setting_item_iface_t *setting_item_iface)
здесь имя параметра - просто hostname

2024-09-23 10:01 UTC, ad7718 commented on main/nv_storage.c
> +esp_err_t nvs_write_u32(const char* key, uint32_t value)
можно упростить так 

```
esp_err_t nvs_write_u8_u16_u32(const char* key, uint32_t value, size_t size)
{
    nvs_handle_t nvs_handle;
    esp_err_t ret = nvs_open("storage", NVS_READWRITE, &nvs_handle);
    if (ret != ESP_OK) {
        return ret;
    }
    switch(size)
    {
        case 1:
            ret = nvs_set_u8(nvs_handle, key, value);
            break;
        case 2:
            ret = nvs_set_u16(nvs_handle, key, value);
            break;
        case 4:
            ret = nvs_set_u32(nvs_handle, key, value);
            break;
        default:
            ret = ESP_ERR_INVALID_ARG;
            break;
    }
    if (ret != ESP_OK) {
        return ret;
    }
    ret = nvs_commit(nvs_handle);
    if (ret != ESP_OK) {
        return ret;
    }
    nvs_close(nvs_handle);
    return ret;
}
```

2024-09-23 10:02 UTC, ad7718 commented on main/nv_storage.c
> +esp_err_t nvs_read_u32(const char* key, uint32_t* value)
аналогично, можно сделть общую функцию

2024-09-23 10:05 UTC, ad7718 commented on unittests/mocks/ram_storage.c
> +int rams_write_u32(const char* key, uint32_t value)
здесь тоже надо сделать общие функции для 8, 16, 32

2024-09-23 10:08 UTC, ad7718 commented on main/constants.h
> +#define DEFAULT_PASS                "admin"
может "wirenboard" по аналогии с WB?

2024-09-25 10:26 UTC, ad7718 requested changes
Осталось несколько незакрытых замечаний, остальное норм

2024-09-25 10:26 UTC, ad7718 commented on main/http_server.c
> +                                    "Uncknown type json item");
тут опечатка и можно на предыдущую строку перенести

2024-09-25 13:18 UTC, ad7718 approved these changes

2024-09-26 03:36 UTC, merged