feature/openapi
wirenboard/wb-mge pull request #10
Opened 2024-10-10 11:08 UTC by ninedev-i

Добавил описание api в формате openapi

2024-10-17 06:17 UTC, AlexeyStrizhnev commented on openapi.yaml
> +                      - true
Если в примере "Invalid login or password", давай тогда тут false

2024-10-17 06:22 UTC, AlexeyStrizhnev commented on openapi.yaml
> +      responses:
Тут нужен requestBody с примером

2024-10-17 06:26 UTC, AlexeyStrizhnev commented on openapi.yaml
> +          content:
Сейчас сделано так, как мы с тобой договорились. То есть тело ответа пустое. Если все ок, то код 200, иначе - 401.

2024-10-17 06:32 UTC, AlexeyStrizhnev commented on openapi.yaml
> +          content:
Давай оставим здесь тело ответа пустым. Сейчас команда get_analysis_data не реализована. И скорее всего для таких вещей будут отдельные эндпоинты. То есть, если все ок, то код 200.

2024-10-17 06:34 UTC, AlexeyStrizhnev commented on openapi.yaml
> +      responses:
Как-то нужно указать, что в requestBody у нас файл прошивки должен загружаться.

2024-10-17 06:42 UTC, AlexeyStrizhnev commented on openapi.yaml
> +        pass:
pass наверно лучше совсем убрать (или сделать отдельную схему). Ситуация: в GET /settings я тебе его не передаю (совсем, даже ключ "pass"), так как при сохранении файла с настройками он туда тоже сохранялся с пустой строкой, а это ломало загрузку этого файла обратно в mge, потому что пароль не может быть пустой строкой. Соответственно в примере для POST запроса, значение "pass": "" так же является некорректным.

2024-10-17 06:46 UTC, AlexeyStrizhnev commented
А почему editor.swagger.io сильно ругается на example и на "openapi: 3.1.0"? Это можно исправить?

2024-10-17 08:14 UTC, ninedev-i commented
> editor.swagger.io

попробуй последнюю версию https://editor-next.swagger.io/

2024-10-17 08:54 UTC, AlexeyStrizhnev commented
Да, в последней версии все норм.

2024-10-17 11:03 UTC, AlexeyStrizhnev requested changes

2024-10-17 11:03 UTC, AlexeyStrizhnev commented on openapi.yaml
> +    TrafficAnalysis:
Это можно убрать.

2025-06-25 12:27 UTC, ad7718 commented
Закрываем, обновили API, переехало в https://github.com/wirenboard/wb-mge/pull/16

2025-06-25 12:27 UTC, closed without merging