Filling system info
wirenboard/wb-mge pull request #11
Opened 2024-10-11 02:45 UTC by AlexeyStrizhnev

Добавлены обработчики сетевых событий, в которых заполняются системные переменные. Так же добавлены обработчики запросов на получение файлов фронта. В Makefile добавлены цели для сборки фронта и проекта в целом. Попутно выполнены некоторые мелкие правки.

2024-10-14 10:28 UTC, ad7718 requested changes

2024-10-14 10:28 UTC, ad7718 commented on main/main.c
> +            sys_info_con_ap++;
у переменной название непонятное

2024-10-14 10:28 UTC, ad7718 commented on main/main.c
> +    mac[5] = 0xAA;
непноятно почему

2024-10-14 10:28 UTC, ad7718 commented on main/main.c
> +static inline void print_setting_items()
тут надо параметр void указать по код стилю, и написать TODO, чтобы не забыть отключитьв релизе. Кстати, если забыть, оно пароли не напечатает?

2024-10-14 15:12 UTC, AlexeyStrizhnev commented on main/main.c
> +            sys_info_con_ap++;
Исправлено

2024-10-14 15:13 UTC, AlexeyStrizhnev commented on main/main.c
> +    mac[5] = 0xAA;
Отлаживался, забыл убрать. Исправлено.

2024-10-14 15:15 UTC, AlexeyStrizhnev commented on main/main.c
> +static inline void print_setting_items()
Исправлено. Пароли не выдаем.

2024-10-15 07:34 UTC, ad7718 approved these changes

2024-10-15 09:37 UTC, merged