feature/FW-666-authorization
wirenboard/wb-mge pull request #5
Opened 2024-09-26 08:32 UTC by AlexeyStrizhnev

В REST-API добавлен функционал авторизации пользователя + незначительный рефакторинг.

2024-09-26 09:41 UTC, ad7718 requested changes

2024-09-26 09:41 UTC, ad7718 commented on main/http_server.c
> +        // Найти и удалить session_id из буфера
я бы сделал static inline функцию вместо комментария. меньше читать, когда не хочешь углублятся в детали, комментарий может протухнуть

2024-09-26 09:41 UTC, ad7718 commented on main/http_server.c
> +    uint32_t value = strtoul(str, &endptr, 10);
а оно точно не читает до бесконечности, если строка бесконечная?

2024-09-26 09:41 UTC, ad7718 commented on main/http_server.c
> +            static int false_val = 0;
const надо добавить. Нельзя как-то по другому здесь сделать?

2024-09-27 08:10 UTC, AlexeyStrizhnev commented on main/http_server.c
> +        // Найти и удалить session_id из буфера
Сделано

2024-09-27 08:10 UTC, AlexeyStrizhnev commented on main/http_server.c
> +    uint32_t value = strtoul(str, &endptr, 10);
Добавил проверки

2024-09-27 08:11 UTC, AlexeyStrizhnev commented on main/http_server.c
> +            static int false_val = 0;
По другому не вышло, но вынес в отдельную функцию.

2024-09-27 09:58 UTC, ad7718 requested changes

2024-09-27 09:58 UTC, ad7718 commented on main/http_server.c
> +uint32_t strtou(const char *u32_str)
а нет готовой нормальной безопасной функции?

2024-09-27 09:58 UTC, ad7718 commented on main/http_server.c
> +    if (strlen(u32_str) > UINT32_STR_MAX_LEN) {
это всё равно будет бесконечно бежать, пока не найдёт '\0'

2024-09-30 09:22 UTC, ad7718 requested changes

2024-09-30 09:22 UTC, ad7718 commented on main/http_server.c
> +    if (errno == ERANGE || value > UINT32_MAX) {
скобки

2024-09-30 10:06 UTC, ad7718 approved these changes

2024-09-30 10:13 UTC, merged